[build-system]
# Minimum requirements for the build system to execute.
requires = [
  "setuptools",
  "wheel",
  "cython>=0.29.2",  # Note: sync with setup.py
  "numpy<=1.16.5; python_version=='2.7'",
  "numpy>=1.17.0; python_version>='3.6'"
]

[tool.black]
target-version = ['py27', 'py35', 'py36', 'py37', 'py38']
exclude = '''
(
  | \.egg
  | \.git
  | build
  | setup.py
)
'''
